# Check here for all configurations: https://starship.rs/config/

format = """
($all\n)\
$directory
$character
"""

right_format = ""
scan_timeout = 10

[username]

[hostname]

[localip]

[shlvl]

[singularity]

[kubernetes]
# symbol = 'ğŸŒŠğŸ³ğŸš¢âš“â›µ'
symbol = 'ğŸ³ '
style = 'dimmed white'
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[directory]
style = 'cyan'
# read_only = " ï ½"
truncation_length = 10
truncate_to_repo = false

[vcsh]

[git_branch]
# symbol = "ï˜ "
style = 'purple'

[git_commit]
style = 'green'

[git_state]
style = 'yellow'

[git_metrics]
added_style = 'green'
deleted_style = 'red'

[git_status]
style = 'red'

[hg_branch]
# symbol = "ï˜ "

[docker_context]
# symbol = "ïŒˆ "

[package]
# symbol = "ï£– "
style = '208'

[buf]
# symbol = "ï’ "

[c]
# symbol = "î˜ "

[cmake]

[cobol]

[container]

# [daml]

[dart]
# symbol = "î˜ "

[deno]

[dotnet]

[elixir]
# symbol = "î‰µ "

[elm]
# symbol = "î˜¬ "

[erlang]

[golang]
# symbol = "î˜§ "

[haskell]
# symbol = "î· "

[helm]

[java]
# symbol = "î‰– "

[julia]
# symbol = "î˜¤ "

[kotlin]

[lua]

[nim]
# symbol = "ïš¤ "

[nodejs]
# symbol = "îœ˜ "

[ocaml]

[perl]

[php]

[pulumi]

[purescript]

[python]
# symbol = "îˆµ "
# symbol = 'ğŸ '
symbol = 'ğŸ‰ '

[rlang]

[red]

[ruby]

[rust]
# symbol = "î¨ "

[scala]

[swift]

[terraform]

[vlang]

[vagrant]

[zig]

[nix_shell]
# symbol = "ï‹œ "

[conda]
# symbol = "ï„Œ "
# symbol = 'ğŸ '
symbol = 'ğŸ‰ '
style = 'green'

[spack]
# symbol = "ğŸ…¢ "

[memory_usage]
# symbol = "ï¡š "

[aws]
# symbol = "îŒ½  "
style = 'yellow'

[gcloud]

[openstack]

[azure]

[env_var]

[crystal]

[custom]

[sudo]

[cmd_duration]

[line_break]
disabled = true

[jobs]

[battery]

[time]

[status]

[shell]

[character]
